"""Run generate_answer.py over the 10 sample questions in
data/eval/sample_questions.csv and save results for manual review.

This is Week 5's "test answer generation on 10 sample questions" step --
no scoring/grading here, just generation + a saved transcript. Week 7 turns
this into a real scored ablation (vector-only vs graph-only vs hybrid) over
a larger 30-40 question set.

Usage:
    python generation/run_sample_questions.py
    python generation/run_sample_questions.py --out docs/week5_sample_answers.md
"""

import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
from common import ENTITIES_CSV, REPO_ROOT, get_logger  # noqa: E402

from generate_answer import answer_question  # noqa: E402
from ollama_client import is_reachable  # noqa: E402

log = get_logger("run_sample_questions")

SAMPLE_QUESTIONS_CSV = REPO_ROOT / "data" / "eval" / "sample_questions.csv"
DEFAULT_OUT = REPO_ROOT / "docs" / "week5_sample_answers.md"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--questions", type=Path, default=SAMPLE_QUESTIONS_CSV)
    parser.add_argument("--entities", type=Path, default=ENTITIES_CSV)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    if not is_reachable():
        log.info("Ollama not reachable -- see docs/manual_setup_ollama.md")
        sys.exit(1)

    questions_df = pd.read_csv(args.questions, keep_default_na=False)
    entities_df = pd.read_csv(args.entities, keep_default_na=False)

    lines = ["# Week 5 sample answers", "", "Generated by `generation/run_sample_questions.py`. Manual review only -- not scored (see Week 7 for the scored ablation).", ""]

    for _, row in questions_df.iterrows():
        log.info(f"{row['id']}: {row['question']}")
        result = answer_question(row["question"], entities_df)
        seed_names = [name for _, name in result["bundle"]["seed_entities"]]

        lines.append(f"## {row['id']} [{row['category']}]: {row['question']}")
        lines.append("")
        lines.append(f"**Seed entities:** {', '.join(seed_names) if seed_names else '(none)'}")
        lines.append("")
        lines.append(f"**Answer:** {result['answer']}")
        lines.append("")
        if row.get("notes"):
            lines.append(f"*Notes: {row['notes']}*")
            lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    log.info(f"wrote {len(questions_df)} answers to {args.out}")


if __name__ == "__main__":
    main()
